l1=[]#empty list
print("Origimal list:",l1)
print("Adding elements")
l1.append(2)
l1.append(8)
l1.append(9)
l1.append(7)
print(l1)
print("Extend:")
l1.extend([3,4,5])
print(l1)
print("Deleting the element")
print("remove() -deletes a particular element")
l1.remove(5)
print(l1)
print("pop-deletes the last element")
print(l1.pop())
print("After deleting the last element")
print(l1)
print("Final list")
print(l1)
